parameters:
    phoenix_base_url: '%env(PHOENIX_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Likes\LikeRepositoryInterface: '@App\Likes\LikeRepository'

    App\Domain\Port\PhoenixClientInterface: '@App\Infrastructure\Http\PhoenixClient'

    App\Infrastructure\Http\PhoenixClient:
        arguments:
            $baseUrl: '%phoenix_base_url%'
