services:
    App\Service\PhoenixClient:
        synthetic: true
        public: true

    App\Service\PhoenixClientInterface: '@App\Service\PhoenixClient'

    test.App\Service\PhoenixClient:
        alias: App\Service\PhoenixClient
        public: true

    test.App\Service\PhoenixClientInterface:
        alias: App\Service\PhoenixClientInterface
        public: true
